{
  "window.zoomLevel": 0,
  "editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace"
  "editor.fontSize": 12,
  "editor.lineHeight": 0,
  "editor.letterSpacing": 0,
  "workbench.editor.tabSizing": "fit",
  "html.format.enable": true,
  "html.format.preserveNewLines": true,
  "files.trimTrailingWhitespace": false,
  "editor.tabSize": 4,
  "editor.cursorStyle": "line",
  "editor.cursorWidth": 0, 
  "editor.wordWrap": "off",
  "editor.multiCursorModifier": "alt",
  "editor.fontWeight": "normal",
  "editor.cursorBlinking": "blink",
  "editor.colorDecorators": true,
  "editor.minimap.enabled": true,
  "workbench.activityBar.visible": true,
  "workbench.sideBar.location": "left",
  "editor.renderWhitespace": "none",
  "editor.rulers": [],
  "editor.minimap.showSlider": "mouseover",
  "workbench.startupEditor": "welcomePage",
  "extensions.ignoreRecommendations": false,
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true
  },
  "workbench.colorTheme": "Default Dark+",
  "workbench.editor.tabCloseButton": "right",
  "emmet.includeLanguages": {},
  "editor.snippetSuggestions": "inline",
  "workbench.editor.enablePreviewFromQuickOpen": true,
  "window.title": "${activeEditorShort}${separator}${rootName}",
  "editor.formatOnSave": false,
  "eslint.autoFixOnSave": false,
  "eslint.alwaysShowStatus": false,
}
